export const products = [
    {
        id: 1,
        nombre: "Cheesecake tipo NY",
        precio: 4000,
        stock: 10,
        image: "https://juanigazcon.github.io/entrega/Images/Productos/cheesecake.jpg",
        image2: "https://juanigazcon.github.io/totus-final/Images/Productos/cheesecake-2.jpg",
        categoryId: 10,
        descripcion:"Base de galletitas con relleno de queso crema dulce. Topping de mermelada y frutos rojos. 28 cm de diámetro, rinde 15/20 porciones."
    }, {
        id: 2,
        nombre: "Rogel",
        precio: 3500,
        stock: 10,
        image: "https://juanigazcon.github.io/entrega/Images/Productos/torta-rogel.jpg",
        categoryId: 10,
        image2: "https://juanigazcon.github.io/totus-final/Images/Productos/rogel-1.jpg",
        descripcion: "10 capas finas, relleno con dulce de leche. Enrejado de merengue suizo. 28 cm de diámetro- 15/20 porciones."
    },
    {
        id: 3,
        nombre: "Marquisse",
        precio: 3800,
        stock: 10,
        image: "https://juanigazcon.github.io/entrega/Images/Productos/marquisse.jpg",
        categoryId: 10,
        descripcion: "Base de brownie súper húmedo y chocolatoso. Mucho dulce de leche, crema chantilly y merengue suizo. 28 cm de diámetro- 15/20 porciones.",
        image2: "https://juanigazcon.github.io/totus-final/Images/Productos/marquisse-1.JPG"
    },
    {
        id: 4,
        nombre: "Torta de Nuez",
        precio: 3800,
        stock: 10,
        image: "https://juanigazcon.github.io/entrega/Images/Productos/torta-nuez.jpg",
        categoryId: 10,
        descripcion: "Base aireada de nuez con dulce de leche y crema chantilly. 28 cm de diámetro- 15/20 porciones.",
        image2: "https://juanigazcon.github.io/totus-final/Images/Productos/torta-nuez-3.jpg"
    },
    {
        id: 5,
        nombre: "Pavlova Clásica",
        precio: 3500,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/pavlova-clasica.jpg",
        descripcion:"Merengue francés, dulce de leche, crema chantilly y lluvia de frutillas. 28 cm de diámetro- 15/20 porciones.",
        image2:"https://juanigazcon.github.io/storage/Images/Productos/pavlova-clasica-2.jpg"
    }, {
        id: 6,
        nombre: "Pavlova Silvestre",
        precio: 4200,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/pavlova-silvestre.jpg",
        descripcion:"Merengue de almendras, dulce de leche, crema de chocolate blanco Y lluvia de frutos rojos.28 cm de diámetro- 15/20 porciones.",
        image2:"https://juanigazcon.github.io/storage/Images/Productos/pavlova-silvestre-2.jpg"

    }, {
        id: 7,
        nombre: "Pavlova de Nuez/Almendras",
        precio: 4000,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/pavlova-fs.jpg",
    }, {
        id: 8,
        nombre: "Key Lemon Pie",
        precio: 3800,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/key-lemon-pie.jpg",
    }, {
        id: 9,
        nombre: "Tarta de Frutillas",
        precio: 3500,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/tarta-frutilla.jpg",
    }, {
        id: 10,
        nombre: "Key Lime Pie",
        precio: 3900,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/key-lime-pie.jpg",
    }, {
        id: 11,
        nombre: "Sablée con Frutos Rojos",
        precio: 4000,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/sable-fr.jpg",
    },
    {
        id: 12,
        nombre: "Lemon Pie",
        precio: 3500,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/lemon-pie.png",
    }, {
        id: 13,
        nombre: "Sablée de Nuez/Almendras",
        precio: 4000,
        stock: 10,
        categoryId: 20,
        image:"https://juanigazcon.github.io/storage/Images/Productos/sablee-fs.jpg",
    }, {
        id: 14,
        nombre: "Chocotorta",
        precio: 4000,
        stock: 10,
        categoryId: 30,
        image:"https://juanigazcon.github.io/storage/Images/Productos/chocotorta.jpg",
    }, {
        id: 15,
        nombre: "Torta Oreo",
        precio: 2800,
        stock: 10,
        categoryId: 30,
        image:"https://juanigazcon.github.io/storage/Images/Productos/torta-oreo.jpg",
    }, {
        id: 16,
        nombre: "Havanet Negro",
        precio: 3200,
        stock: 10,
        categoryId: 30,
        image:"https://juanigazcon.github.io/storage/Images/Productos/havannet-negro.jpg",
    },
    {
        id: 17,
        nombre: "Havanet Blanco",
        precio: 3200,
        stock: 10,
        categoryId: 30,
        image:"https://juanigazcon.github.io/storage/Images/Productos/havannet-blanco.jpg",
    }, 
    {
        id: 18,
        nombre: "Layer Cake",
        precio: 5500,
        stock: 10,
        categoryId: 40,
        image:"https://juanigazcon.github.io/storage/Images/Productos/layer-cake.jpg",
    },
    {
        id: 19,
        nombre: "Cookie Cake",
        precio: 4500,
        stock: 10,
        categoryId: 40,
        image:"https://juanigazcon.github.io/storage/Images/Productos/cookie-cake.jpg",
    }, {
        id: 20,
        nombre: "Macarons",
        precio: 1100,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/macarons.png",
    }, {
        id: 21,
        nombre: "Brownies",
        precio: 1200,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/brownies.jpg",
    }, {
        id: 22,
        nombre: "Alfajorcitos Clásicos",
        precio: 1200,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/alfajorcitos-clasicos.jpg",
    }, {
        id: 23,
        nombre: "Alfajorcitos de Nuez/Almendras",
        precio: 1400,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/alfajorcitos-nuez-alm.jpg",
    }, {
        id: 24,
        nombre: "Alfajores Blockazo",
        precio: 1000,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/blockazo.jpg",
    }, {
        id: 25,
        nombre: "Coquitos",
        precio: 1000,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/coquitos.jpg",
    }, {
        id: 26,
        nombre: "Alfajores de Maicena",
        precio: 1200,
        stock: 10,
        categoryId: 50,
        image:"https://juanigazcon.github.io/storage/Images/Productos/maicena.jpg",
    }

]